const PLACES = {
  'tubbataha-reef': {
    name: 'Tubbataha Reef',
    subtitle: 'Heart of the Coral Triangle',
    tag: 'UNESCO · Sulu Sea',
    category: 'visayas', type: 'marine', region: 'Sulu Sea', season: 'Mar–Jun',
    threat: true,
    threatReason: 'Threatened by climate-driven coral bleaching, illegal fishing by foreign vessels, and inadequate patrol coverage across its vast remote expanse in the Sulu Sea.',
    image: 'image/Tubataha reef.jpg',
    description: 'A remote atoll rising from the depths of the Sulu Sea — accessible only by liveaboard for three months a year. Tubbataha holds 360 coral species, 600 fish species, and nesting populations of sharks and sea turtles on atolls untouched by daily human contact. Its fish biomass rivals the most pristine mid-Pacific reefs, and its waters shelter the Scalloped Hammerhead, one of the ocean\'s most threatened sharks.',
    funfact: 'Tubbataha is only accessible by liveaboard for about 3 months a year due to sea conditions. The rest of the year it is completely off-limits — which is precisely why it remains so pristine. Its remoteness is its greatest protection.',
    badges: ['UNESCO Heritage', 'Marine Protected Area', 'Hammerhead Sharks', '600+ Fish Species'],
    wildlife: ['Scalloped Hammerhead', 'Sea Turtles', 'Reef Sharks', 'Manta Ray']
  },
  'mount-hamiguitan-range': {
    name: 'Mount Hamiguitan Range',
    subtitle: 'Pygmy Forest of Mindanao',
    tag: 'UNESCO · Davao Oriental',
    category: 'mindanao', type: 'highland', region: 'Davao Oriental', season: 'Mar–Jun',
    threat: false, threatReason: '',
    image: 'image/Sierra Madre.jpg',
    description: 'A UNESCO World Heritage Site inscribed in 2014 for its extraordinary range of ecosystems — from lowland dipterocarp forest to a rare pygmy forest at its 1,637m summit. Shelters 341 plant species, 177 animals, and carnivorous pitcher plants endemic to its peaks, including the critically endangered Philippine Eagle.',
    funfact: 'Mount Hamiguitan is one of the very few places on Earth where a complete elevational gradient — from tropical dipterocarp forest at sea level to pygmy forest at the summit — survives entirely intact within a single protected area.',
    badges: ['UNESCO Heritage', 'Pygmy Forest', 'Endemic Species', 'Pitcher Plants'],
    wildlife: ['Philippine Eagle', 'Pitcher Plants', 'Endemic Orchids']
  },
  'sierra-madre': {
    name: 'Sierra Madre',
    subtitle: 'Last Great Forest Frontier',
    tag: 'Forest Frontier · Luzon',
    category: 'luzon', type: 'wildlife', region: 'Aurora · Luzon', season: 'Nov–May',
    threat: true,
    threatReason: 'Under sustained pressure from illegal logging, slash-and-burn agriculture, and mining concessions steadily eroding Luzon\'s last great forest frontier.',
    image: 'image/Sierra Madre.jpg',
    description: 'The longest mountain range in the Philippines and the country\'s last great forest frontier. Shelters the Philippine Crocodile, Philippine Eagle, and thousands of endemic species in one of Asia\'s largest remaining rainforest blocks.',
    funfact: 'The Sierra Madre acts as a natural barrier protecting Metro Manila from the full force of Pacific typhoons. Without this mountain range, the capital would be far more exposed to catastrophic storm damage.',
    badges: ['Forest Frontier', 'Typhoon Barrier', 'Endemic Wildlife', 'Luzon'],
    wildlife: ['Philippine Crocodile', 'Philippine Eagle', 'Cloud Rat']
  },
  'mount-apo': {
    name: 'Mount Apo',
    subtitle: 'Roof of the Philippines',
    tag: 'National Park · Mindanao',
    category: 'mindanao', type: 'highland', region: 'Davao · Mindanao', season: 'Mar–May',
    threat: false, threatReason: '',
    image: 'image/Mt. Apo.jpg',
    description: 'The Philippines\' highest peak at 2,954m — home of the Philippine Eagle. Ancient rainforests, hot springs, and geothermal activity make Apo one of the country\'s most dramatic natural destinations.',
    funfact: 'Mount Apo means \'grandfather\' or \'master\' in several Mindanao languages. Its geothermal energy now powers a significant portion of Mindanao\'s electricity grid — the mountain literally lights up the island.',
    badges: ['Highest Peak', '2,954m', 'National Park', 'Geothermal'],
    wildlife: ['Philippine Eagle', 'Philippine Deer', 'Mindanao Bleeding-heart']
  },
  'mayon-volcano': {
    name: 'Mayon Volcano',
    subtitle: 'The Perfect Cone',
    tag: 'Active Volcano · Luzon',
    category: 'luzon', type: 'volcanic', region: 'Albay · Bicol', season: 'Nov–Apr',
    threat: false, threatReason: '',
    image: 'image/Mayon Volcano.jpg',
    description: 'The world\'s most perfect volcanic cone towers over the Bicol region. The surrounding Mayon Biosphere Reserve shelters lowland forests rich in endemic species — and the volcano itself is in constant, beautiful activity.',
    funfact: 'The name Mayon comes from \'Magayon\' — meaning beautiful in Bicolano. Local legend says the volcano is the body of a beautiful princess named Daragang Magayon, buried there after a tragic love story.',
    badges: ['Perfect Cone', 'Active Volcano', 'Biosphere Reserve', 'Albay'],
    wildlife: []
  },
  'agusan-marsh': {
    name: 'Agusan Marsh',
    subtitle: 'Floating Islands of Mindanao',
    tag: 'Wetland · Mindanao',
    category: 'mindanao', type: 'wildlife', region: 'Agusan del Sur · Mindanao', season: 'Nov–Apr',
    threat: true,
    threatReason: 'Threatened by drainage for agriculture, settlement encroachment, and pollution from upstream gold mining operations in the Agusan River watershed.',
    image: 'image/Agusan Marsh.jpg',
    description: 'One of Southeast Asia\'s largest freshwater swamp forests — a mosaic of lakes, floating islands, and floodplain forest. Home to the Philippine Crocodile, Estuarine Crocodile, and rare waterbirds.',
    funfact: 'The floating islands of Agusan Marsh physically move with the seasons — entire plant communities drift across the marsh, shifting the landscape every year. Indigenous Manobo communities have lived on and with them for generations.',
    badges: ['Wetland Reserve', 'Floating Islands', 'Ramsar Site', 'Manobo Heritage'],
    wildlife: ['Philippine Crocodile', 'Estuarine Crocodile', 'Purple Heron']
  },
  'chocolate-hills': {
    name: 'Chocolate Hills',
    subtitle: 'Geological Wonder of Bohol',
    tag: 'Geological Wonder · Bohol',
    category: 'visayas', type: 'cultural', region: 'Bohol · Visayas', season: 'Nov–May',
    threat: true,
    threatReason: 'Quarrying on outer hills and invasive grass species are altering the monument\'s distinctive landscape, while growing tourism accelerates erosion.',
    image: 'image/Chocolate hills.jpg',
    description: 'Over 1,700 conical limestone mounds turn chocolate-brown in the dry season. A Philippine National Geological Monument and one of the most recognisable landscapes in Southeast Asia.',
    funfact: 'Local Bohol legend says the Chocolate Hills were formed from the tears of a heartbroken giant who wept over a lost love, and his tears solidified into the hills we see today.',
    badges: ['National Geological Monument', '1,700+ Hills', 'Bohol', 'Limestone Karst'],
    wildlife: ['Philippine Tarsier']
  },
  'puerto-princesa-subterranean-river-national-park': {
    name: 'Puerto Princesa Subterranean River National Park',
    subtitle: 'World\'s Longest Navigable Underground River',
    tag: 'UNESCO · Region IV-B',
    category: 'luzon', type: 'wildlife', region: 'Palawan · Region IV-B', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan Underground River.jpg',
    description: 'The Puerto Princesa Subterranean River navigates 8.2km beneath Palawan\'s limestone karst before emptying into the sea. One of the world\'s longest navigable underground rivers and a UNESCO World Heritage Site.',
    funfact: 'The Underground River empties directly into the South China Sea — making it one of the few places on Earth where a navigable underground river meets the open ocean. At low tide, saltwater flows back into the cave entrance.',
    badges: ['UNESCO Heritage', '8.2km Underground', 'Limestone Karst', 'New 7 Wonders of Nature'],
    wildlife: ['Cave Swiftlets', 'Monitor Lizard', 'Long-tailed Macaque']
  },
  'mount-pulag': {
    name: 'Mount Pulag',
    subtitle: 'Playground of the Gods',
    tag: 'Highland · Luzon',
    category: 'luzon', type: 'highland', region: 'Benguet · Cordillera', season: 'Oct–Apr',
    threat: false, threatReason: '',
    image: 'image/Mt. Pulag.jpg',
    description: 'Luzon\'s highest peak at 2,922m — known for its "sea of clouds" and rare dwarf bamboo grasslands. A sacred mountain to the indigenous Ibaloi and Kalanguya peoples of the Cordillera.',
    funfact: 'The Ibaloi people call Mount Pulag \'Playground of the Gods.\' On summit mornings, the cloud sea below makes it feel like you are standing on top of the world — a white ocean stretching to every horizon.',
    badges: ['2,922m', 'Sea of Clouds', 'Sacred Mountain', 'Ibaloi Heritage'],
    wildlife: ['Luzon Bleeding-heart', 'Philippine Deer', 'Mossy Forest Birds']
  },
  'mt-pandadagsaan': {
    name: 'Mt. Pandadagsaan',
    subtitle: 'The White Peak',
    tag: 'Highland Peak · Mindanao',
    category: 'mindanao', type: 'highland', region: 'Mindanao', season: 'Nov–Apr',
    threat: false, threatReason: '',
    image: 'image/Sierra Madre.jpg',
    description: 'Known as White Peak for its pale rocky summit rising above the montane forests of Mindanao. A highland trekking destination offering sweeping views across the surrounding ranges, with mossy forest trails sheltering endemic orchids, pitcher plants, and mountain birds.',
    funfact: 'Mt. Pandadagsaan earned the name \'White Peak\' from the pale limestone and light-coloured rock exposed at its summit — which glows distinctly bright against the surrounding green montane forest when viewed from the valleys below.',
    badges: ['White Peak', 'Mossy Forest', 'Endemic Orchids', 'Pitcher Plants'],
    wildlife: ['Endemic Orchids', 'Pitcher Plants', 'Mountain Birds']
  },
  'taal-volcano-lake': {
    name: 'Taal Volcano & Lake',
    subtitle: 'A Volcano Within a Lake Within a Volcano',
    tag: 'Active Volcano · Batangas',
    category: 'luzon', type: 'volcanic', region: 'Batangas · Luzon', season: 'Nov–May',
    threat: true,
    threatReason: 'The endemic Tawilis sardine faces extinction from overfishing, lake eutrophication from fish pens, and water chemistry damage from the January 2020 eruption.',
    image: 'image/Taal.jpg',
    description: 'One of the world\'s most unique volcanic systems — an active island volcano rising from a crater lake, itself enclosed within one of the largest calderas in Southeast Asia. Home to the endemic Tawilis sardine and a dramatic landscape sculpted by centuries of eruptions.',
    funfact: 'Taal Lake holds the world\'s only freshwater sardine — the Tawilis (Sardinella tawilis) — a species found in no other lake on Earth. The same lake surrounds an active volcano that sits inside a larger volcanic crater, making it a volcano within a lake within a volcano.',
    badges: ['Active Volcano', 'Freshwater Sardine', 'Caldera Lake', 'Batangas'],
    wildlife: ['Tawilis Sardine', 'Philippine Duck', 'Water Monitor']
  },
  'mount-pinatubo': {
    name: 'Mount Pinatubo',
    subtitle: 'The Sleeping Giant Awakened',
    tag: 'Crater Lake · Zambales',
    category: 'luzon', type: 'volcanic', region: 'Zambales · Luzon', season: 'Dec–May',
    threat: false, threatReason: '',
    image: 'image/Mt. Pinatubo.jpg',
    description: 'The site of the 20th century\'s second-largest volcanic eruption now harbours a stunning turquoise crater lake ringed by lahar-sculpted badlands. The surrounding Aeta communities have lived in relationship with the volcano for thousands of years.',
    funfact: 'The 1991 eruption of Mount Pinatubo was the second-largest volcanic eruption of the 20th century. So much ash and sulfur dioxide was ejected into the stratosphere that it temporarily cooled the entire planet\'s temperature by 0.5°C for over a year.',
    badges: ['Crater Lake', '1991 Eruption', 'Turquoise Lake', 'Aeta Heritage'],
    wildlife: ['Forest Birds', 'Monitor Lizard']
  },
  'camiguin': {
    name: 'Camiguin',
    subtitle: 'Island Born of Fire',
    tag: 'Volcanic Island · Northern Mindanao',
    category: 'mindanao', type: 'volcanic', region: 'Northern Mindanao', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Camiguin.jpg',
    description: 'Called the "Island Born of Fire," Camiguin holds seven volcanoes on an island smaller than many cities. Its waters shelter the Camiguin Flying Fox (Critically Endangered), its cold springs and reefs are among the clearest in the Visayan Sea, and Mount Hibok-Hibok looms active above it all.',
    funfact: 'Camiguin has more volcanoes per square kilometre than any other island on Earth. One of its eruptions in 1871 was so violent it submerged an entire cemetery — whose cross now stands visible just offshore at low tide.',
    badges: ['7 Volcanoes', 'Most Volcanic Island', 'Crystal Springs', 'Camiguin Flying Fox'],
    wildlife: ['Camiguin Flying Fox', 'Sea Turtles', 'Reef Fish']
  },
  'apo-island': {
    name: 'Apo Island',
    subtitle: 'Proof That Community Protection Works',
    tag: 'Marine Sanctuary · Negros Oriental',
    category: 'visayas', type: 'marine', region: 'Negros Oriental · Visayas', season: 'Mar–Jun',
    threat: true,
    threatReason: 'Repeated coral bleaching from rising sea temperatures has damaged reef structure, while growing visitor numbers are straining the community management system.',
    image: 'image/Apo Island.jpg',
    description: 'A tiny volcanic island surrounded by one of Southeast Asia\'s most celebrated community-managed marine sanctuaries. Green sea turtles gather here year-round, reef fish biomass rivals pristine mid-Pacific reefs, and the surrounding wall dives are among the most dramatic in the Philippines.',
    funfact: 'Apo Island\'s marine sanctuary, established in 1982, is one of the world\'s oldest community-managed marine reserves. Fish biomass inside the sanctuary is more than five times higher than in unprotected areas.',
    badges: ['Community Sanctuary', 'Since 1982', 'Green Turtles', 'Wall Diving'],
    wildlife: ['Green Sea Turtle', 'Hawksbill Turtle', 'Reef Sharks', 'Grouper']
  },
  'siargao-island': {
    name: 'Siargao Island',
    subtitle: 'Surf Capital of the Philippines',
    tag: 'Surf Capital · Surigao del Norte',
    category: 'mindanao', type: 'marine', region: 'Surigao del Norte · Mindanao', season: 'Aug–Nov',
    threat: false, threatReason: '',
    image: 'image/Tubataha reef.jpg',
    description: 'The Philippines\' surfing capital — a teardrop-shaped island fringed by mangroves, lagoons, and world-class reef breaks. Beyond Cloud 9, Siargao shelters the Sohoton Cove, whose crystal caves flood at high tide, and the Magpupungko rock pools that only appear at low water.',
    funfact: 'Siargao\'s Cloud 9 surf break became internationally famous only in the 1990s when foreign surfers first documented it. The island\'s unique geography — sitting directly in the path of Pacific swells — produces powerful, hollow waves that break over a shallow reef.',
    badges: ['Cloud 9 Surf', 'Mangrove Lagoons', 'Sohoton Cove', 'Pacific Swells'],
    wildlife: ['Reef Fish', 'Sea Turtles', 'Stingless Jellyfish']
  },
  'el-nido': {
    name: 'El Nido',
    subtitle: 'Ancient Limestone at the Coral Triangle\'s Edge',
    tag: 'Marine Park · Palawan · Region IV-B',
    category: 'luzon', type: 'marine', region: 'Northern Palawan · Region IV-B', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan Karst.jpg',
    description: 'A maze of ancient limestone cliffs, hidden lagoons, and white sand beaches at the northern tip of Palawan. The El Nido–Taytay Managed Resource Protected Area covers over 900 km² of some of the most biodiverse marine habitat in the Coral Triangle.',
    funfact: 'The limestone karst towers of El Nido rise directly from the sea — some reaching over 300 metres. These formations began as coral reefs some 30 million years ago, and the fossils of ancient marine life are still visible within the rock walls above the waterline.',
    badges: ['Limestone Karst', '30 Million Years Old', 'Hidden Lagoons', 'Coral Triangle'],
    wildlife: ['Sea Turtles', 'Reef Fish', 'Philippine Cockatoo', 'Dugong']
  },
  'coron-kayangan-lake': {
    name: 'Coron & Kayangan Lake',
    subtitle: 'Ancient Karst and Asia\'s Clearest Lake',
    tag: 'Karst Lakes · Palawan · Region IV-B',
    category: 'luzon', type: 'marine', region: 'Palawan · Region IV-B', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan Karst.jpg',
    description: 'Coron\'s jagged limestone peaks — among the oldest karst formations in Palawan — rise dramatically from turquoise waters. Kayangan Lake, fed entirely by underground springs filtering through ancient karst rock, is rated among Asia\'s clearest lakes. The surrounding cliffs and forest shelter endemic birds, roosting flying foxes, and monitor lizards descending to the water\'s edge.',
    funfact: 'Kayangan Lake sits inside an ancient limestone crater — its water so clear that visibility extends to the bottom, fed entirely by underground springs filtering through millions of years of karst rock. The surrounding cliffs are among the oldest exposed limestone formations in Palawan.',
    badges: ['Kayangan Lake', 'Ancient Karst', 'Underground Springs', 'Palawan'],
    wildlife: ['Flying Fox', 'Monitor Lizard', 'Sea Turtles', 'Reef Fish']
  },
  'lake-sebu': {
    name: 'Lake Sebu',
    subtitle: 'Highland Lake of the T\'boli People',
    tag: 'Highland Lake · South Cotabato',
    category: 'mindanao', type: 'highland', region: 'South Cotabato · Mindanao', season: 'Year-round',
    threat: false, threatReason: '',
    image: 'image/Agusan Marsh.jpg',
    description: 'A highland lake ringed by hills and T\'boli communities in South Cotabato. The surrounding forests shelter endemic birds, the lake itself is home to rare freshwater species, and the Seven Falls cascade through one of the most culturally rich landscapes in Mindanao.',
    funfact: 'Lake Sebu\'s Seven Falls hold deep spiritual significance for the T\'boli people, whose epic song-poem Tudbulul describes the spirit of the falls as a guardian of the land. The T\'boli are celebrated for the dream-woven T\'nalak cloth, produced only by women called Fu Dalu.',
    badges: ['Seven Falls', 'T\'boli Culture', 'T\'nalak Cloth', 'Highland Lake'],
    wildlife: ['Endemic Freshwater Fish', 'Forest Birds']
  },
  'donsol-whale-shark-trail': {
    name: 'Donsol Whale Shark Trail',
    subtitle: 'Whale Shark Capital of the World',
    tag: 'Eco-Tourism · Sorsogon',
    category: 'luzon', type: 'marine', region: 'Sorsogon · Luzon', season: 'Nov–Jun',
    threat: false, threatReason: '',
    image: 'image/Whale Shark Butanding.jpg',
    description: 'The whale shark capital of the world — a small fishing town where butanding (whale sharks) gather in extraordinary numbers from November to June, feeding on plankton in the warm Ticao Pass. Interaction is strictly regulated: no touching, no flash, snorkel only — a global model for sustainable wildlife tourism.',
    funfact: 'Donsol is where the world first learned that whale sharks could be reliably encountered in the wild. Before the late 1990s, whale shark aggregations of this scale were unknown to science — local fishermen had simply been living alongside them for generations.',
    badges: ['Whale Sharks', 'Butanding', 'Sustainable Tourism', 'Sorsogon'],
    wildlife: ['Whale Shark', 'Manta Ray', 'Spinner Dolphin']
  },
  'apo-reef': {
    name: 'Apo Reef',
    subtitle: 'The Philippines\' Largest Coral Reef',
    tag: 'Natural Park · Occidental Mindoro',
    category: 'luzon', type: 'marine', region: 'Occidental Mindoro · Sulu Sea', season: 'Mar–Jun',
    threat: true,
    threatReason: 'Despite protected status, Apo Reef faces persistent poaching by foreign and domestic fishing vessels — limited patrol boats make remote enforcement difficult.',
    image: 'image/Tubataha reef.jpg',
    description: 'The world\'s second-largest contiguous coral reef system and the Philippines\' largest coral reef — a remote atoll rising from the Sulu Sea between Mindoro and Palawan. Its outer walls plunge hundreds of metres into the deep, drawing hammerhead sharks, thresher sharks, and massive schools of barracuda.',
    funfact: 'Apo Reef was declared a protected area in 1996, but local fishermen had been destroying it for decades before enforcement began. Today its recovery is considered one of the most successful large-scale reef rehabilitation stories in the Philippines.',
    badges: ['Largest Coral Reef', 'Hammerhead Sharks', 'Remote Atoll', 'Sulu Sea'],
    wildlife: ['Hammerhead Shark', 'Thresher Shark', 'Barracuda', 'Sea Turtles']
  },
  'callao-cave-homo-luzonensis': {
    name: 'Callao Cave & Homo luzonensis',
    subtitle: 'Where a New Human Species Was Found',
    tag: 'Natural Cave · Cagayan',
    category: 'luzon', type: 'cultural', region: 'Cagayan · Luzon', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan Underground River.jpg',
    description: 'A seven-chambered limestone cave on the banks of the Pinacanauan River in Cagayan — where sunlight streams through a natural skylight to illuminate a chapel inside the cave. Its deeper passages yielded bones of Homo luzonensis, rewriting the timeline of human presence in Southeast Asia.',
    funfact: 'Callao Cave is where archaeologists in 2019 announced the discovery of Homo luzonensis — a previously unknown human species that lived in the Philippines at least 50,000 years ago. The cave became one of the most scientifically significant sites in all of Southeast Asian prehistory.',
    badges: ['Homo luzonensis', '50,000 Years', 'Limestone Cave', 'Prehistoric Site'],
    wildlife: ['Cave Bats', 'Cave Swiftlets']
  },
  'balicasag-island': {
    name: 'Balicasag Island',
    subtitle: 'Three Decades of Community Protection',
    tag: 'Marine Sanctuary · Bohol',
    category: 'visayas', type: 'marine', region: 'Bohol · Visayas', season: 'Mar–Jun',
    threat: true,
    threatReason: 'Rising sea temperatures have triggered repeated bleaching events, and tour boat groundings have caused direct physical damage to portions of the wall reef.',
    image: 'image/Apo Island.jpg',
    description: 'A tiny coral island off the southwestern tip of Bohol, encircled by a wall reef that drops vertically into deep water. Green and hawksbill sea turtles rest on the reef plateau year-round, spinner dolphins ride the currents offshore, and the no-take sanctuary zone has allowed the reef to recover to near-pristine condition.',
    funfact: 'Balicasag Island\'s marine sanctuary was established in 1985 and is one of the oldest no-take zones in the Philippines. A single hectare of healthy reef here supports more fish biomass than many entire reef systems elsewhere in Southeast Asia.',
    badges: ['Since 1985', 'No-Take Zone', 'Wall Diving', 'Sea Turtles'],
    wildlife: ['Green Sea Turtle', 'Hawksbill Turtle', 'Spinner Dolphin', 'Reef Sharks']
  },
  'olango-island-wildlife-sanctuary': {
    name: 'Olango Island Wildlife Sanctuary',
    subtitle: 'Siberia to Australia — One Stop at a Time',
    tag: 'Wildlife Sanctuary · Cebu',
    category: 'visayas', type: 'wildlife', region: 'Cebu · Visayas', season: 'Sep–Nov',
    threat: true,
    threatReason: 'Coastal reclamation projects across Cebu Bay are steadily reducing the tidal flats that tens of thousands of migratory shorebirds depend on to refuel each year.',
    image: 'image/Agusan Marsh.jpg',
    description: 'A Ramsar-listed wetland and one of the most important migratory bird stopovers in Southeast Asia. Every year tens of thousands of shorebirds — including globally threatened species like the Chinese Egret and Far Eastern Curlew — rest and refuel on Olango\'s tidal flats before continuing south to Australia.',
    funfact: 'Olango Island\'s tidal flats are so rich in invertebrates that they attract over 48 species of migratory shorebirds — some flying non-stop from breeding grounds in Siberia and Alaska. It is one of only a handful of critical stopover points in the entire East Asian–Australasian Flyway south of Japan.',
    badges: ['Ramsar Wetland', '48 Shorebird Species', 'Migratory Flyway', 'Cebu'],
    wildlife: ['Chinese Egret', 'Far Eastern Curlew', 'Migratory Shorebirds']
  },
  'sohoton-cove': {
    name: 'Sohoton Cove',
    subtitle: 'Millions of Stingless Jellyfish',
    tag: 'Natural Cove & Cave · Samar',
    category: 'visayas', type: 'wildlife', region: 'Northern Samar · Visayas', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan Underground River.jpg',
    description: 'A hidden tidal cove in Northern Samar reachable only at low tide through a narrow limestone passage. Inside, the brackish water teems with millions of stingless jellyfish, cathedral-ceilinged caves glow with bioluminescent organisms, and the forest canopy above shelters rare hornbills and flying foxes.',
    funfact: 'The jellyfish of Sohoton Cove are stingless because the enclosed lagoon has no predators to threaten them — so over thousands of generations they lost their venom. Swim among millions of jellyfish with no risk of a sting.',
    badges: ['Stingless Jellyfish', 'Tidal Cove', 'Bioluminescence', 'Northern Samar'],
    wildlife: ['Stingless Jellyfish', 'Flying Fox', 'Hornbills', 'Cave Bats']
  },
  'mount-kanlaon-natural-park': {
    name: 'Mount Kanlaon Natural Park',
    subtitle: 'The Visayas\' Most Active Volcano',
    tag: 'Natural Park · Negros',
    category: 'visayas', type: 'volcanic', region: 'Negros · Visayas', season: 'Mar–May',
    threat: true,
    threatReason: 'Forest clearing for agriculture on the lower slopes has pushed critically endangered Negros endemic birds into ever-smaller high-elevation forest refuges.',
    image: 'image/Mt. Apo.jpg',
    description: 'An active stratovolcano and the highest peak in the Visayas, its montane forests sheltering critically endangered Visayan birds found nowhere else — including the Visayan Flowerpecker and Writhed Hornbill. The national park is one of the last intact forest sanctuaries on the heavily deforested island of Negros.',
    funfact: 'Mount Kanlaon is the most active volcano in the Visayas, with over 30 recorded eruptions since 1866. Its summit crater sits at 2,465 metres and is often shrouded in mist — making it one of the most atmospheric and challenging climbs in the Philippine archipelago.',
    badges: ['Active Volcano', '2,465m', 'Endemic Birds', 'Negros'],
    wildlife: ['Visayan Flowerpecker', 'Writhed Hornbill', 'Negros Bleeding-heart']
  },
  'hinatuan-enchanted-river': {
    name: 'Hinatuan Enchanted River',
    subtitle: 'The Impossibly Blue River',
    tag: 'River Sanctuary · Surigao del Sur',
    category: 'mindanao', type: 'wildlife', region: 'Surigao del Sur · Mindanao', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Hinatuan Enchanted River.jpg',
    description: 'A short but impossibly deep river in Surigao del Sur — its water an otherworldly cobalt blue fed by underwater springs connecting to the open sea. Saltwater fish from the ocean swim freely upriver, surrounding swimmers. At noon each day, all visitors are asked to leave the water for the "Fish Feeding" — and thousands of fish surface at once.',
    funfact: 'The blue colour of the Hinatuan Enchanted River is so vivid and uniform that early scientists suspected it was artificially coloured. The hue comes from the extraordinary depth and clarity of the water, which absorbs all warm wavelengths of light, scattering only deep blue back to the surface.',
    badges: ['Cobalt Blue', 'Underwater Springs', 'Ocean-connected', 'Surigao del Sur'],
    wildlife: ['Ocean Fish', 'Freshwater Species', 'Monitor Lizard']
  },
  'lake-lanao': {
    name: 'Lake Lanao',
    subtitle: 'One Million Years of Isolation',
    tag: 'Ancient Lake · Lanao del Sur',
    category: 'mindanao', type: 'wildlife', region: 'Lanao del Sur · Mindanao', season: 'Year-round',
    threat: true,
    threatReason: 'Introduced tilapia and decades of overfishing have driven most endemic fish species to near-extinction — one of the most acute freshwater biodiversity crises in the Philippines.',
    image: 'image/Agusan Marsh.jpg',
    description: 'The Philippines\' second-largest lake and one of Southeast Asia\'s most ancient — a vast freshwater body in the Mindanao highlands sacred to the Maranao people. Its isolation produced one of the world\'s most remarkable freshwater fish radiations, with endemic species now critically threatened by introduced competitors and habitat change.',
    funfact: 'Lake Lanao is estimated to be over a million years old. This antiquity allowed its endemic fish to evolve in total isolation, producing a flock of species found absolutely nowhere else on Earth. Tragically, introduced tilapia and overfishing have driven most of these endemics to extinction within living memory.',
    badges: ['1 Million Years Old', 'Ancient Lake', 'Maranao Sacred', 'Endemic Fish'],
    wildlife: ['Endemic Cyprinids', 'Philippine Freshwater Crocodile']
  },
  'aliwagwag-falls': {
    name: 'Aliwagwag Falls',
    subtitle: '84 Tiers Through Old-Growth Rainforest',
    tag: 'Waterfall & Forest · Davao Oriental',
    category: 'mindanao', type: 'wildlife', region: 'Davao Oriental · Mindanao', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Sierra Madre.jpg',
    description: 'Eighty-four cascading tiers plunge 340 metres through old-growth rainforest in Davao Oriental — one of the tallest multi-tiered waterfalls in Southeast Asia. The surrounding Pujada Bay Protected Landscape is a frontier wilderness of intact lowland dipterocarp forest, undisturbed coral reefs, and undescribed endemic species.',
    funfact: 'Aliwagwag Falls drops across 84 tiers over a vertical descent of 340 metres. The surrounding forest is so remote that new plant species are still being described from its watershed.',
    badges: ['84 Tiers', '340m Descent', 'Old-Growth Forest', 'Davao Oriental'],
    wildlife: ['Philippine Eagle', 'Endemic Plants', 'Forest Birds']
  },
  'lake-holon': {
    name: 'Lake Holon',
    subtitle: 'The Forbidden Lake of the T\'boli',
    tag: 'Crater Lake · South Cotabato',
    category: 'mindanao', type: 'volcanic', region: 'South Cotabato · Mindanao', season: 'Mar–May',
    threat: false, threatReason: '',
    image: 'image/Mt. Apo.jpg',
    description: 'One of the Philippines\' most pristine crater lakes, nestled inside the summit caldera of Mount Parker in South Cotabato. Reached by a two-day trek through mossy montane forest, Holon\'s emerald waters are surrounded by endemic pitcher plants, wild orchids, and the rich T\'boli cultural landscape of the highlands.',
    funfact: 'The T\'boli call Lake Holon \'Maughan\' — the forbidden lake — and it was off-limits to outsiders for generations. It was formally opened to trekkers only in the 2000s, and its surrounding forest remains almost entirely intact.',
    badges: ['Crater Lake', 'T\'boli Sacred', 'Pitcher Plants', 'Mossy Forest'],
    wildlife: ['Pitcher Plants', 'Wild Orchids', 'Mountain Birds']
  },
  'philippine-eagle-center': {
    name: 'Philippine Eagle Center',
    subtitle: 'Last Hope for the National Bird',
    tag: 'Conservation Center · Davao City',
    category: 'mindanao', type: 'wildlife', region: 'Davao City · Mindanao', season: 'Year-round',
    threat: false, threatReason: '',
    image: 'image/Agila.jpg',
    description: 'The primary conservation breeding facility for the Philippine Eagle — the country\'s national bird and one of the world\'s most endangered raptors. Home to rescued and captive-bred eagles in large naturalistic enclosures, the center leads research into eagle ecology and runs education programs reaching thousands of students annually.',
    funfact: 'The Philippine Eagle Center has successfully bred the Philippine Eagle in captivity — a feat considered nearly impossible for large raptors. Each captive-bred eagle costs more to raise than a human university education, reflecting how demanding and rare these birds truly are.',
    badges: ['Captive Breeding', 'National Bird', 'Conservation Research', 'Davao City'],
    wildlife: ['Philippine Eagle', 'Philippine Deer', 'Philippine Crocodile']
  },
  'mts-iglit-baco-natural-park': {
    name: 'Mts. Iglit-Baco Natural Park',
    subtitle: 'Last Stronghold of the Tamaraw',
    tag: 'Natural Park · Occidental Mindoro',
    category: 'luzon', type: 'wildlife', region: 'Occidental Mindoro · Luzon', season: 'Nov–May',
    threat: true,
    threatReason: 'The Tamaraw population has collapsed from over 10,000 in the early 20th century to fewer than 500 today, driven by habitat loss from agricultural encroachment and past hunting.',
    image: 'image/Tamaraw.jpg',
    description: 'The last stronghold of the Tamaraw — the critically endangered dwarf buffalo found only on Mindoro. Its montane grasslands and forest mosaic shelter fewer than 500 remaining individuals of one of the world\'s rarest large mammals, alongside the Mindoro Bleeding-heart Dove and endemic forest birds.',
    funfact: 'The Tamaraw is found on one island and one island only — Mindoro. It has never existed anywhere else on Earth. Despite being a buffalo, it is a solitary animal — living and foraging alone in the mountain forest rather than in herds.',
    badges: ['Last Stronghold', 'Tamaraw', 'Fewer than 500', 'Mindoro Endemic'],
    wildlife: ['Tamaraw', 'Mindoro Bleeding-heart', 'Philippine Deer', 'Endemic Birds']
  },
  'samar-island-natural-park': {
    name: 'Samar Island Natural Park',
    subtitle: 'Largest Lowland Rainforest in the Visayas',
    tag: 'Natural Park · Eastern Samar',
    category: 'visayas', type: 'wildlife', region: 'Eastern Samar · Visayas', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Sierra Madre.jpg',
    description: 'The largest intact lowland rainforest in the Visayas — a vast karst and forest wilderness sheltering the Philippine Cockatoo, Samar Cobra, and rare cave-dwelling species in one of the most geologically complex island interiors in the archipelago. Its limestone cave systems rival those of Palawan in scale.',
    funfact: 'Samar Island Natural Park contains the largest remaining block of lowland rainforest in the Visayas — a forest so intact that the Philippine Warty Pig, considered locally extinct elsewhere in the region, still maintains a viable population inside its boundaries.',
    badges: ['Largest Visayas Forest', 'Limestone Caves', 'Philippine Cockatoo', 'Samar'],
    wildlife: ['Philippine Cockatoo', 'Philippine Warty Pig', 'Samar Cobra', 'Cave Species']
  },
  'calauit-wildlife-sanctuary': {
    name: 'Calauit Wildlife Sanctuary',
    subtitle: 'Africa Meets the Philippines',
    tag: 'Wildlife Sanctuary · Palawan · Region IV-B',
    category: 'luzon', type: 'wildlife', region: 'Northern Palawan · Region IV-B', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Philippine Calamian Deer.jpg',
    description: 'An extraordinary island sanctuary in northern Palawan where African savanna animals — giraffes, zebras, and impalas — share habitat with endemic Philippine species including the Calamian Deer, Palawan Bearcats, and Philippine Cockatoos. A surreal and ecologically unique conservation experiment with a complex human history.',
    funfact: 'Calauit\'s African animals were brought to Palawan in 1976, displacing the indigenous Tagbanwa community to create an African game reserve. Today giraffes, zebras, impalas, and waterbucks roam freely alongside endemic Philippine species, creating the world\'s most unusual wildlife overlap.',
    badges: ['African & Philippine Wildlife', 'Giraffes in PH', 'Calamian Deer', 'Palawan'],
    wildlife: ['Calamian Deer', 'Palawan Bearcat', 'Philippine Cockatoo', 'Giraffe', 'Zebra']
  },
  'kapurpurawan-rock-formation': {
    name: 'Kapurpurawan Rock Formation',
    subtitle: 'White Cliffs of the Luzon Strait',
    tag: 'Rock Formation · Ilocos Norte',
    category: 'luzon', type: 'geological', region: 'Ilocos Norte · Luzon', season: 'Nov–Apr',
    threat: false, threatReason: '',
    address: 'Burgos, Ilocos Norte',
    image: 'image/Kapurpurawan  Rock Formation.jpg',
    description: 'A rare coastal outcrop of calcium carbonate-rich sedimentary rock sculpted by millennia of wind and wave erosion along the Luzon Strait. Its blindingly white surface — caused by dense concentrations of calcium carbonate from ancient marine organisms — rises dramatically from the wave-battered shoreline of Burgos, Ilocos Norte. The formation is most dramatic at low tide, when the full base is exposed and the contrast between white rock, dark volcanic cobbles, and turquoise sea is at its sharpest. Strong Luzon Strait winds have carved the surface into ridged and pitted textures unique among Philippine coastal formations.',
    funfact: 'Kapurpurawan means "to make white" in Ilocano. The rock\'s brilliant white surface is formed from the same material as cave stalactites — calcium carbonate deposited by ancient marine organisms — now exposed and continuously shaped by centuries of sea and wind erosion along the Luzon Strait.',
    badges: ['Calcium Carbonate', 'Wave-Sculpted', 'Luzon Strait', 'Burgos'],
    wildlife: []
  },
  'la-paz-sand-dunes': {
    name: 'La Paz Sand Dunes',
    subtitle: 'Desert of the North',
    tag: 'Sand Dunes · Ilocos Norte',
    category: 'luzon', type: 'geological', region: 'Ilocos Norte · Luzon', season: 'Nov–Apr',
    threat: false, threatReason: '',
    address: 'Laoag City, Ilocos Norte',
    image: 'image/La Paz sand dunes.jpg',
    description: 'An 85 km² coastal sand desert in Laoag City — one of the largest active dune systems in the Philippines, shaped by the northeast monsoon winds sweeping in from the South China Sea. The dunes rise up to 30 metres and abruptly border irrigated rice fields and scrubland — one of the more striking ecological contrasts in northern Luzon. After each monsoon season, wind-sculpted ridgelines shift and reform, leaving the landscape visually different from visit to visit.',
    funfact: 'The La Paz dunes are alive and moving — the prevailing northeast monsoon pushes sand steadily inland each year, slowly burying vegetation and occasionally reclaiming farmland at the dune\'s advancing edge. The dune field is one of the few places in the Philippines where off-road sandboarding is possible.',
    badges: ['Active Dune System', '30m Dunes', 'Northeast Monsoon', 'Laoag City'],
    wildlife: ['Asian Golden Plover', 'Pacific Reef Heron', 'Little Tern']
  },
  'kabigan-falls': {
    name: 'Kabigan Falls',
    subtitle: 'Hidden Cascade of Pagudpud',
    tag: 'Waterfall · Ilocos Norte',
    category: 'luzon', type: 'highland', region: 'Ilocos Norte · Luzon', season: 'Jun–Nov',
    threat: false, threatReason: '',
    address: 'Balaoi, Pagudpud, Ilocos Norte',
    image: 'image/Kabigan Falls.jpg',
    description: 'A 27-metre single-drop waterfall set within dense forest in Balaoi, Pagudpud — accessible via a 15-minute forest trail from the trailhead. The Kabigan River plunges into a wide natural pool ringed by old-growth canopy, one of the most accessible wilderness waterfalls along the northern Ilocos coastline. Fed by streams draining the Sierra Madre foothill range, the river reaches peak flow during the southwest monsoon — the falls at full volume send spray and mist across the entire pool basin.',
    funfact: 'Kabigan Falls sits just a few kilometres inland from the Pagudpud coast — yet the forest is dense enough that the roar of the waterfall reaches you before you can see it through the canopy. The trail crosses the river multiple times before arriving at the base.',
    badges: ['27m Drop', 'Forest Trail', 'River Crossing', 'Pagudpud'],
    wildlife: ['Philippine Kingfisher', 'Blue-naped Parrot', 'Large-billed Crow']
  },
  'bantay-abot-cave': {
    name: 'Bantay Abot Cave',
    subtitle: 'Mountain with a Hole',
    tag: 'Rock Arch · Ilocos Norte',
    category: 'luzon', type: 'geological', region: 'Ilocos Norte · Luzon', season: 'Nov–Apr',
    threat: false, threatReason: '',
    address: 'Balaoi, Pagudpud, Ilocos Norte',
    image: 'image/Bantay abot Cave.jpg',
    description: 'A natural coastal rock arch carved entirely by wave erosion along the Pagudpud shoreline. The name means "mountain with a hole" in Ilocano — an apt description of the arch\'s dramatic perforation through solid coastal rock. At high tide, waves surge through the arch and emerge as spray on the landward side — the funnelled wind through the opening creates strong updrafts that attract seabirds and Pacific Swallows riding the coastal thermals.',
    funfact: 'Bantay Abot was formed by the same relentless wave action that carved Kapurpurawan to the south — but where Kapurpurawan was shaped from soft calcium carbonate, Bantay Abot punched clean through harder coastal rock, leaving a full natural arch standing above the sea.',
    badges: ['Natural Sea Arch', 'Wave Erosion', 'Coastal Updrafts', 'Pagudpud'],
    wildlife: ['Edible-nest Swiftlet', 'Collared Kingfisher', 'Pacific Swallow']
  },
  'pagudpud-blue-lagoon': {
    name: 'Pagudpud Blue Lagoon',
    subtitle: 'Cerulean Cove of the Far North',
    tag: 'Coastal Lagoon · Ilocos Norte',
    category: 'luzon', type: 'marine', region: 'Ilocos Norte · Luzon', season: 'Nov–Apr',
    threat: false, threatReason: '',
    address: 'Saud, Pagudpud, Ilocos Norte',
    image: 'image/Pagudpud Blue Lagoon.jpg',
    description: 'A vivid cerulean cove near Dos Hermanos Islands in Pagudpud, where crystal-clear turquoise water meets a white sand shoreline framed by old-growth canopy. One of the most northerly white-sand beaches in the Philippines, sheltered from open Pacific swells by the Dos Hermanos Islands offshore. The islands break the prevailing ocean swell and create the unusually calm, lagoon-like conditions that give the beach its name — coral patches in the shallows support small reef fish communities, and Green Sea Turtles have been reported foraging along the cove edges.',
    funfact: 'Pagudpud sits at the northwestern tip of Luzon where the South China Sea and the Luzon Strait meet — making it one of the few beaches in the Philippines where you can watch the sun rise and set over open water from the same shoreline on the same day.',
    badges: ['Blue Lagoon', 'Dos Hermanos Islands', 'Coral Shallows', 'Far North Luzon'],
    wildlife: ['Green Sea Turtle']
  },
  'pinsal-falls': {
    name: 'Pinsal Falls',
    subtitle: 'Largest Waterfall of Ilocandia',
    tag: 'Waterfall · Ilocos Sur',
    category: 'luzon', type: 'highland', region: 'Ilocos Sur · Luzon', season: 'Jun–Nov',
    threat: false, threatReason: '',
    address: 'Santa Maria, Ilocos Sur',
    image: 'image/Pinsal Falls ILocos Sur.jpg',
    description: 'A powerful 85-foot twin-cascade waterfall dropping from a wide limestone ledge into twin plunge basins flanked by canyon walls in Santa Maria, Ilocos Sur — the largest waterfall in the Ilocos Region. Fed by rivers draining the western Cordillera slopes, the falls run at their most dramatic during the southwest monsoon when peak flow sends white sheets of water across the full width of the limestone ledge. The gorge walls are draped in limestone canyon forest of ferns, mosses, and spray-adapted species thriving in the perpetual mist zone.',
    funfact: 'Pinsal Falls sits just an hour from Vigan City — one of the most visited historic destinations in the Philippines — yet it remains largely unknown to most visitors. The largest waterfall in Ilocandia stands a short drive north of one of the country\'s most famous heritage towns.',
    badges: ['85-Foot Drop', 'Twin Cascade', 'Limestone Gorge', 'Santa Maria'],
    wildlife: ['Brown-breasted Kingfisher', 'Coleto', 'Balicassiao']
  },
  'pikkang-falls': {
    name: 'Pikkang Falls',
    subtitle: 'Hidden Curtain of San Juan',
    tag: 'Waterfall · Ilocos Sur',
    category: 'luzon', type: 'highland', region: 'Ilocos Sur · Luzon', season: 'Jun–Nov',
    threat: false, threatReason: '',
    address: 'Barangay Malamin, San Juan, Ilocos Sur',
    image: 'image/Pinsal Falls ILocos Sur.jpg',
    description: 'A curtain-style multi-cascade waterfall in Barangay Malamin, San Juan — reached via a 30-minute trek that crosses the river multiple times before arriving at the base. The falls spread across a wide rock face in overlapping sheets of white water, creating a natural amphitheatre of spray and mist. Far less visited than Pinsal Falls to the north, Pikkang is one of the more rewarding off-trail waterfalls along the Cordillera\'s western foothills.',
    funfact: 'Pikkang\'s curtain formation is caused by bedrock that dips outward at the lip — rather than concentrating at a single point, the river fans laterally across the full rock face, producing a wide veil of water instead of a single plunging column.',
    badges: ['Curtain Waterfall', 'River Crossing Trek', 'San Juan', 'Ilocos Sur'],
    wildlife: []
  },
  'tangadan-falls': {
    name: 'Tangadan Falls',
    subtitle: 'Twin-Drop of the Baroro River',
    tag: 'Waterfall · La Union',
    category: 'luzon', type: 'highland', region: 'La Union · Luzon', season: 'Jun–Nov',
    threat: false, threatReason: '',
    address: 'Barangay Poblacion, San Gabriel, La Union',
    image: 'image/Kabigan Falls.jpg',
    description: 'A two-tier waterfall along the Baroro River in San Gabriel — one of La Union\'s most accessible highland destinations despite lying at the foot of the Cordillera. The lower drop descends roughly 15 metres into a wide natural plunge pool cold enough even in summer, fed by Cordillera snowmelt and mountain springs. The trek follows the river upstream through bamboo groves and second-growth forest, crossing the Baroro three times before reaching the base of the falls.',
    funfact: 'The Baroro River that feeds Tangadan Falls is one of the few rivers in the Ilocos region that drains the western Cordillera directly into the South China Sea — carrying cold, mineral-rich highland water year-round even during the dry season.',
    badges: ['Two-Tier Falls', 'Baroro River', 'Cordillera Highlands', 'San Gabriel'],
    wildlife: ['Purple Heron', 'Brown-breasted Kingfisher', 'Brahminy Kite']
  },
  'immuki-island': {
    name: 'Immuki Island',
    subtitle: 'Coral Rock Island of Balaoan',
    tag: 'Coral Island · La Union',
    category: 'luzon', type: 'marine', region: 'La Union · Luzon', season: 'Nov–May',
    threat: false, threatReason: '',
    address: 'Off Barangay Balaoan, Balaoan, La Union',
    image: 'image/Pagudpud Blue Lagoon.jpg',
    description: 'A compact dead-coral island lying offshore from Balaoan — formed from compacted coral rock rather than sand or sediment, giving it a pale, bleached appearance surrounded by crystal-clear water. Tidal pools and natural channels cut across its surface at low tide, exposing small reef-flat lagoons ideal for wading and snorkelling. The surrounding shallows sit directly on La Union\'s narrow continental shelf, with visibility reaching the sandy bottom in calm conditions.',
    funfact: 'Immuki is technically a cay — an island formed entirely from coral rubble and reef debris rather than volcanic or sedimentary rock. Its flat, low profile means the highest point is just a few metres above sea level, making it one of La Union\'s most ephemeral landscapes.',
    badges: ['Coral Rock Island', 'Tidal Pools', 'Snorkelling', 'Balaoan'],
    wildlife: ['Brahminy Kite', 'Pacific Reef Egret']
  },
  'palawan': {
    name: 'Palawan',
    subtitle: 'The Last Frontier',
    tag: 'UNESCO World Heritage · Region IV-B · MIMAROPA',
    category: 'luzon', type: 'wildlife', region: 'Region IV-B · MIMAROPA', season: 'Nov–May',
    threat: false, threatReason: '',
    image: 'image/Palawan.jpg',
    description: 'Stretching 450 kilometres from Mindoro to Borneo, Palawan is the Philippines\' most biodiverse island. Its forests contain some of the last intact lowland dipterocarp stands in Southeast Asia. The Puerto Princesa Subterranean River — the world\'s longest navigable underground river — runs 8.2 kilometres beneath the limestone karst before emptying into the South China Sea.',
    funfact: 'Palawan has more than 1,700 islands and islets of its own. Despite being the Philippines\' largest province, its population density is one of the lowest in the country — much of it remains wild and roadless.',
    badges: ['UNESCO Heritage', 'Last Frontier', 'Underground River', 'Coral Triangle'],
    wildlife: ['Irrawaddy Dolphin', 'Philippine Cockatoo', 'Palawan Peacock-Pheasant', 'Palawan Bearcat']
  }
};
