/* ─────────────────────────────────────────────
   species-data.js  —  Expedition PH
   Single source of truth for all species.
   Fields: name, sci, status, group, tag, island, profiled
   Status codes: CR · EN · VU · NT · LC · DD · EX · PE · RD
───────────────────────────────────────────── */

const SPECIES = [

  /* ══════════════════════════════════════════
     BIRDS
  ══════════════════════════════════════════ */
  { name:'Philippine Eagle',            sci:'Pithecophaga jefferyi',           status:'CR', group:'birds',       tag:'Raptor',        island:'Mindanao · Luzon · Leyte · Samar',  profiled:true  },
  { name:'Philippine Cockatoo',         sci:'Cacatua haematuropygia',          status:'CR', group:'birds',       tag:'Parrot',        island:'Palawan · Sulu',                     profiled:true  },
  { name:'Philippine Hornbill',         sci:'Buceros hydrocorax',              status:'VU', group:'birds',       tag:'Hornbill',      island:'Luzon · Samar · Leyte',              profiled:true  },
  { name:"Palawan Peacock-Pheasant",    sci:'Polyplectron napoleonis',         status:'VU', group:'birds',       tag:'Pheasant',      island:'Palawan',                            profiled:true  },
  { name:'Luzon Bleeding-Heart Dove',   sci:'Gallicolumba luzonica',           status:'VU', group:'birds',       tag:'Dove',          island:'Luzon',                              profiled:true  },
  { name:'Mindoro Bleeding-Heart Dove', sci:'Gallicolumba platenae',           status:'CR', group:'birds',       tag:'Dove',          island:'Mindoro',                            profiled:true  },
  { name:'Philippine Eagle-Owl',        sci:'Bubo philippensis',               status:'VU', group:'birds',       tag:'Owl',           island:'Luzon · Mindanao · Leyte · Samar',   profiled:true  },
  { name:"Walden's Hornbill",           sci:'Rhabdotorrhinus waldeni',         status:'CR', group:'birds',       tag:'Hornbill',      island:'Panay · Negros',                     profiled:true  },
  { name:'Philippine Forest Duck',      sci:'Anas luzonica',                   status:'VU', group:'birds',       tag:'Waterfowl',     island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Cebu Flowerpecker',           sci:'Dicaeum quadricolor',             status:'CR', group:'birds',       tag:'Flowerpecker',  island:'Cebu',                               profiled:false },
  { name:'Philippine Serpent Eagle',    sci:'Spilornis holospilus',            status:'LC', group:'birds',       tag:'Raptor',        island:'Widespread',                         profiled:true  },
  { name:'Sulu Hornbill',               sci:'Anthracoceros montani',           status:'CR', group:'birds',       tag:'Hornbill',      island:'Sulu Archipelago',                   profiled:true  },
  { name:'Philippine Hanging Parrot',   sci:'Loriculus philippensis',          status:'LC', group:'birds',       tag:'Parrot',        island:'Luzon · Visayas',                    profiled:true  },
  { name:'Giant Scops Owl',             sci:'Otus gurneyi',                    status:'VU', group:'birds',       tag:'Owl',           island:'Mindanao · Leyte',                   profiled:true  },
  { name:'Flaming Sunbird',             sci:'Aethopyga flagrans',              status:'LC', group:'birds',       tag:'Sunbird',       island:'Luzon · Visayas',                    profiled:true  },
  { name:'Lowland White-eye',           sci:'Zosterops meyeni',                status:'LC', group:'birds',       tag:'White-eye',     island:'Luzon',                              profiled:true  },
  { name:'Philippine Falconet',         sci:'Microhierax erythrogenys',        status:'LC', group:'birds',       tag:'Raptor',        island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Hawk-Eagle',       sci:'Nisaetus philippensis',           status:'VU', group:'birds',       tag:'Raptor',        island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Trogon',           sci:'Harpactes ardens',                status:'NT', group:'birds',       tag:'Trogon',        island:'Luzon · Visayas · Mindanao',         profiled:true  },
  { name:'Philippine Pitta',            sci:'Erythropitta erythrogaster',      status:'LC', group:'birds',       tag:'Pitta',         island:'Widespread',                         profiled:true  },
  { name:'Blue-naped Parrot',           sci:'Tanygnathus lucionensis',         status:'NT', group:'birds',       tag:'Parrot',        island:'Widespread',                         profiled:true  },
  { name:'Philippine Kingfisher',       sci:'Ceyx melanurus',                  status:'EN', group:'birds',       tag:'Kingfisher',    island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Bulbul',           sci:'Hypsipetes philippinus',          status:'LC', group:'birds',       tag:'Bulbul',        island:'Widespread',                         profiled:true  },
  { name:"Johnstone's Lorikeet",        sci:'Trichoglossus johnstoniae',       status:'VU', group:'birds',       tag:'Parrot',        island:'Mindanao',                           profiled:true  },
  /* — unprofile birds — */
  { name:'Sulu Bleeding-Heart',         sci:'Gallicolumba menagei',            status:'CR', group:'birds',       tag:'Dove',          island:'Sulu Archipelago',                   profiled:false },
  { name:'Negros Bleeding-Heart',       sci:'Gallicolumba keayi',              status:'CR', group:'birds',       tag:'Dove',          island:'Negros · Mindanao',                  profiled:false },
  { name:'Mindanao Bleeding-Heart',     sci:'Gallicolumba crinigera',          status:'VU', group:'birds',       tag:'Dove',          island:'Mindanao · Basilan',                 profiled:false },
  { name:'Guaiabero',                   sci:'Bolbopsittacus lunulatus',        status:'VU', group:'birds',       tag:'Parrot',        island:'Luzon · Samar · Leyte · Mindanao',   profiled:false },
  { name:'Camiguin Hawk-Owl',           sci:'Ninox leventisi',                 status:'EN', group:'birds',       tag:'Owl',           island:'Camiguin',                           profiled:false },
  { name:'Luzon Hornbill',              sci:'Penelopides manillae',            status:'NT', group:'birds',       tag:'Hornbill',      island:'Luzon · Marinduque',                 profiled:false },
  { name:'Panay Hornbill',              sci:'Penelopides panini',              status:'EN', group:'birds',       tag:'Hornbill',      island:'Panay · Masbate',                    profiled:false },
  { name:'Mindanao Hornbill',           sci:'Penelopides affinis',             status:'NT', group:'birds',       tag:'Hornbill',      island:'Mindanao · Basilan',                 profiled:false },
  { name:'Writhed Hornbill',            sci:'Rhabdotorrhinus leucocephalus',   status:'VU', group:'birds',       tag:'Hornbill',      island:'Mindanao · Basilan · Sulu',          profiled:false },
  { name:'Cebu Black Shama',            sci:'Copsychus cebuensis',             status:'CR', group:'birds',       tag:'Thrush',        island:'Cebu',                               profiled:false },
  { name:'Philippine Leafbird',         sci:'Chloropsis flavipennis',          status:'EN', group:'birds',       tag:'Leafbird',      island:'Cebu · Negros · Leyte',              profiled:true  },
  { name:'Negros Striped Babbler',      sci:'Zosterornis nigrorum',            status:'EN', group:'birds',       tag:'Babbler',       island:'Negros',                             profiled:false },
  { name:'Philippine Magpie-Robin',     sci:'Copsychus mindanensis',           status:'LC', group:'birds',       tag:'Thrush',        island:'Mindanao · Visayas',                 profiled:false },
  { name:'Philippine Minivet',          sci:'Pericrocotus lansbergei',         status:'NT', group:'birds',       tag:'Minivet',       island:'Palawan',                            profiled:false },
  { name:'Philippine Scops Owl',        sci:'Otus megalotis',                  status:'LC', group:'birds',       tag:'Owl',           island:'Luzon · Mindanao · Leyte',           profiled:false },
  { name:'Blue-backed Parrot',          sci:'Tanygnathus sumatranus',          status:'NT', group:'birds',       tag:'Parrot',        island:'Palawan · Sulu',                     profiled:false },
  { name:'Philippine Swamphen',         sci:'Porphyrio pulverulentus',         status:'LC', group:'birds',       tag:'Rail',          island:'Widespread',                         profiled:false },
  { name:'Philippine Duck',             sci:'Anas luzonica',                   status:'VU', group:'birds',       tag:'Waterfowl',     island:'Widespread',                         profiled:false },
  { name:'Steere\'s Pitta',             sci:'Erythropitta steerii',            status:'VU', group:'birds',       tag:'Pitta',         island:'Mindanao · Leyte · Samar',           profiled:false },
  { name:'Mindanao Wattled Broadbill',  sci:'Sarcophanops steerii',            status:'VU', group:'birds',       tag:'Broadbill',     island:'Mindanao',                           profiled:false },
  { name:'Visayan Broadbill',           sci:'Sarcophanops samarensis',         status:'EN', group:'birds',       tag:'Broadbill',     island:'Samar · Leyte',                      profiled:false },

  /* ══════════════════════════════════════════
     MAMMALS
  ══════════════════════════════════════════ */
  { name:'Philippine Tarsier',              sci:'Carlito syrichta',            status:'NT', group:'mammals',     tag:'Primate',       island:'Bohol · Samar · Leyte · Mindanao',   profiled:true  },
  { name:'Tamaraw',                         sci:'Bubalus mindorensis',         status:'CR', group:'mammals',     tag:'Bovid',         island:'Mindoro',                            profiled:true  },
  { name:'Philippine Pangolin',             sci:'Manis culionensis',           status:'CR', group:'mammals',     tag:'Pangolin',      island:'Palawan',                            profiled:true  },
  { name:'Visayan Warty Pig',               sci:'Sus cebifrons',               status:'CR', group:'mammals',     tag:'Pig',           island:'Negros · Panay',                     profiled:true  },
  { name:'Palawan Bearcat',                 sci:'Arctictis binturong whitei',  status:'VU', group:'mammals',     tag:'Viverrid',      island:'Palawan',                            profiled:true  },
  { name:'Giant Golden-crowned Flying Fox', sci:'Acerodon jubatus',            status:'EN', group:'mammals',     tag:'Megabat',       island:'Luzon · Mindanao · Leyte',           profiled:true  },
  { name:'Visayan Spotted Deer',            sci:'Rusa alfredi',                status:'EN', group:'mammals',     tag:'Deer',          island:'Panay · Negros',                     profiled:true  },
  { name:'Philippine Deer',                 sci:'Rusa marianna',               status:'VU', group:'mammals',     tag:'Deer',          island:'Widespread',                         profiled:true  },
  { name:'Philippine Naked-backed Fruit Bat',sci:'Dobsonia chapmani',         status:'CR', group:'mammals',     tag:'Megabat',       island:'Negros · Cebu',                      profiled:true  },
  { name:'Philippine Warty Pig',            sci:'Sus philippensis',            status:'VU', group:'mammals',     tag:'Pig',           island:'Luzon · Mindanao · Visayas',         profiled:true  },
  { name:'Palawan Stink Badger',            sci:'Mydaus marchei',              status:'LC', group:'mammals',     tag:'Mustelid',      island:'Palawan',                            profiled:true  },
  { name:'Calamian Deer',                   sci:'Axis calamianensis',          status:'EN', group:'mammals',     tag:'Deer',          island:'Calamian Islands',                   profiled:true  },
  { name:'Northern Luzon Giant Cloud Rat',  sci:'Phloeomys pallidus',          status:'LC', group:'mammals',     tag:'Rodent',        island:'Luzon',                              profiled:true  },
  { name:'Philippine Mouse-Deer',           sci:'Tragulus nigricans',          status:'EN', group:'mammals',     tag:'Chevrotain',    island:'Balabac Island',                     profiled:true  },
  { name:'Apomys',                          sci:'Apomys spp.',                 status:'DD', group:'mammals',     tag:'Rodent',        island:'Luzon',                              profiled:true  },
  { name:'Crunomys',                        sci:'Crunomys spp.',               status:'DD', group:'mammals',     tag:'Rodent',        island:'Mindanao',                           profiled:true  },
  { name:'Panay Cloudrunner',               sci:'Crateromys heaneyi',          status:'EN', group:'mammals',     tag:'Rodent',        island:'Panay',                              profiled:true  },
  { name:'Limnomys',                        sci:'Limnomys sibuanus',           status:'VU', group:'mammals',     tag:'Rodent',        island:'Mindanao',                           profiled:true  },
  { name:'Bullimus',                        sci:'Bullimus spp.',               status:'VU', group:'mammals',     tag:'Rodent',        island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Batomys',                         sci:'Batomys spp.',                status:'VU', group:'mammals',     tag:'Rodent',        island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Colugo',               sci:'Cynocephalus volans',         status:'LC', group:'mammals',     tag:'Colugo',        island:'Mindanao · Visayas · Luzon',         profiled:true  },
  { name:'Palawan Porcupine',               sci:'Hystrix pumila',              status:'VU', group:'mammals',     tag:'Rodent',        island:'Palawan',                            profiled:true  },
  { name:'Philippine Tube-nosed Bat',       sci:'Nyctimene rabori',            status:'CR', group:'mammals',     tag:'Bat',           island:'Negros',                             profiled:true  },
  { name:'Crateromys',                      sci:'Crateromys spp.',             status:'EN', group:'mammals',     tag:'Rodent',        island:'Luzon · Mindanao',                   profiled:true  },
  /* — unprofile mammals — */
  { name:'Mindanao Gymnure',                sci:'Podogymnura truei',           status:'EN', group:'mammals',     tag:'Gymnure',       island:'Mindanao',                           profiled:false },
  { name:'Palawan Treeshrew',               sci:'Tupaia palawanensis',         status:'LC', group:'mammals',     tag:'Treeshrew',     island:'Palawan',                            profiled:false },
  { name:'Malayan Flying Fox',              sci:'Pteropus vampyrus',           status:'EN', group:'mammals',     tag:'Megabat',       island:'Widespread',                         profiled:false },
  { name:'Golden-mantled Flying Fox',       sci:'Pteropus pumilus',            status:'VU', group:'mammals',     tag:'Megabat',       island:'Luzon · Mindanao',                   profiled:false },
  { name:'Mindanao Tree Shrew',             sci:'Urogale everetti',            status:'VU', group:'mammals',     tag:'Treeshrew',     island:'Mindanao',                           profiled:false },
  { name:'Philippine Horseshoe Bat',        sci:'Rhinolophus philippinensis',  status:'LC', group:'mammals',     tag:'Bat',           island:'Widespread',                         profiled:false },
  { name:'Southern Luzon Giant Cloud Rat',  sci:'Phloeomys cumingi',          status:'LC', group:'mammals',     tag:'Rodent',        island:'Luzon',                              profiled:false },
  { name:'Mt. Apo Shrew-Rat',               sci:'Chrotomys gonzalesi',         status:'EN', group:'mammals',     tag:'Rodent',        island:'Mindanao',                           profiled:false },
  { name:'Palawan Flying Squirrel',         sci:'Hylopetes nigripes',          status:'NT', group:'mammals',     tag:'Rodent',        island:'Palawan',                            profiled:false },
  { name:'Camiguin Forest Rat',             sci:'Rattus camiguinensis',        status:'EN', group:'mammals',     tag:'Rodent',        island:'Camiguin',                           profiled:false },

  /* ══════════════════════════════════════════
     REPTILES & AMPHIBIANS
  ══════════════════════════════════════════ */
  { name:'Philippine Crocodile',         sci:'Crocodylus mindorensis',         status:'CR', group:'reptiles',    tag:'Crocodilian',   island:'Luzon · Mindanao · Palawan',         profiled:true  },
  { name:'Philippine Cobra',             sci:'Naja philippinensis',            status:'LC', group:'reptiles',    tag:'Snake',         island:'Luzon · Mindoro · Masbate',          profiled:true  },
  { name:'Philippine Pit Viper',         sci:'Trimeresurus flavomaculatus',    status:'VU', group:'reptiles',    tag:'Viper',         island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Sailfin Lizard',    sci:'Hydrosaurus pustulatus',         status:'VU', group:'reptiles',    tag:'Lizard',        island:'Luzon · Mindanao · Samar',           profiled:true  },
  { name:'Philippine Forest Turtle',     sci:'Siebenrockiella leytensis',      status:'CR', group:'reptiles',    tag:'Turtle',        island:'Leyte · Samar · Mindanao',           profiled:true  },
  { name:'Samar Cobra',                  sci:'Naja samarensis',                status:'LC', group:'reptiles',    tag:'Snake',         island:'Visayas · Mindanao',                 profiled:true  },
  { name:"Gray's Monitor",               sci:'Varanus olivaceus',              status:'VU', group:'reptiles',    tag:'Monitor',       island:'Luzon',                              profiled:true  },
  { name:'Ornate Monitor',               sci:'Varanus ornatus',                status:'VU', group:'reptiles',    tag:'Monitor',       island:'Luzon',                              profiled:true  },
  { name:'Philippine Flying Dragon',     sci:'Draco volans',                   status:'LC', group:'reptiles',    tag:'Lizard',        island:'Widespread',                         profiled:true  },
  { name:'Tokay Gecko',                  sci:'Gekko gecko',                    status:'LC', group:'reptiles',    tag:'Gecko',         island:'Widespread',                         profiled:true  },
  { name:'Philippine Sun Skink',         sci:'Eutropis multicarinata',         status:'LC', group:'reptiles',    tag:'Skink',         island:'Widespread',                         profiled:true  },
  { name:'Green Sea Turtle',             sci:'Chelonia mydas',                 status:'EN', group:'reptiles',    tag:'Sea Turtle',    island:'Widespread Coast',                   profiled:true  },
  { name:'Hawksbill Sea Turtle',         sci:'Eretmochelys imbricata',         status:'CR', group:'reptiles',    tag:'Sea Turtle',    island:'Widespread Coast',                   profiled:true  },
  { name:'King Cobra',                   sci:'Ophiophagus hannah',             status:'VU', group:'reptiles',    tag:'Snake',         island:'Widespread',                         profiled:true  },
  { name:'Reticulated Python',           sci:'Malayopython reticulatus',       status:'LC', group:'reptiles',    tag:'Snake',         island:'Widespread',                         profiled:true  },
  { name:'Blue-lipped Sea Krait',        sci:'Laticauda laticaudata',          status:'LC', group:'reptiles',    tag:'Snake',         island:'Widespread Coast',                   profiled:true  },
  { name:'Water Monitor',                sci:'Varanus salvator',               status:'LC', group:'reptiles',    tag:'Monitor',       island:'Widespread',                         profiled:true  },
  { name:'Philippine Forest Dragon',     sci:'Gonocephalus sophiae',           status:'LC', group:'reptiles',    tag:'Lizard',        island:'Luzon',                              profiled:true  },
  { name:'Philippine Soft-shell Turtle', sci:'Pelochelys cantorii',            status:'EN', group:'reptiles',    tag:'Turtle',        island:'Luzon · Palawan',                    profiled:true  },
  { name:'Philippine Giant Forest Frog', sci:'Limnonectes leytensis',          status:'VU', group:'reptiles',    tag:'Frog',          island:'Leyte · Mindanao',                   profiled:true  },
  { name:'Mindanao Horned Forest Frog',  sci:'Ceratobatrachus guentheri',      status:'LC', group:'reptiles',    tag:'Frog',          island:'Mindanao · Sulu',                    profiled:true  },
  { name:'Philippine Flying Frog',       sci:'Rhacophorus pardalis',           status:'LC', group:'reptiles',    tag:'Frog',          island:'Palawan · Mindanao',                 profiled:true  },
  { name:'Philippine Rat Snake',         sci:'Ptyas luzonensis',               status:'LC', group:'reptiles',    tag:'Snake',         island:'Luzon',                              profiled:true  },
  { name:'Palawan Horned Frog',          sci:'Megophrys ligayae',              status:'VU', group:'reptiles',    tag:'Frog',          island:'Palawan',                            profiled:true  },
  /* — unprofile reptiles & amphibians — */
  { name:'Palawan Monitor',              sci:'Varanus palawanensis',           status:'LC', group:'reptiles',    tag:'Monitor',       island:'Palawan',                            profiled:false },
  { name:'Philippine Flat-headed Snake', sci:'Oligodon spp.',                  status:'DD', group:'reptiles',    tag:'Snake',         island:'Luzon',                              profiled:false },
  { name:'Philippine Blind Snake',       sci:'Malayotyphlops spp.',            status:'DD', group:'reptiles',    tag:'Snake',         island:'Widespread',                         profiled:false },
  { name:'Leatherback Sea Turtle',       sci:'Dermochelys coriacea',           status:'VU', group:'reptiles',    tag:'Sea Turtle',    island:'Widespread Coast',                   profiled:false },
  { name:'Olive Ridley Sea Turtle',      sci:'Lepidochelys olivacea',          status:'VU', group:'reptiles',    tag:'Sea Turtle',    island:'Widespread Coast',                   profiled:false },
  { name:'Palawan Spitting Cobra',       sci:'Naja sumatrana',                 status:'LC', group:'reptiles',    tag:'Snake',         island:'Palawan',                            profiled:false },
  { name:'Philippine Ground Gecko',      sci:'Gekko mindorensis',              status:'LC', group:'reptiles',    tag:'Gecko',         island:'Mindoro',                            profiled:false },
  { name:'Giant Philipppine Skink',      sci:'Tiliqua scincoides',             status:'LC', group:'reptiles',    tag:'Skink',         island:'Widespread',                         profiled:false },
  { name:'Mindanao Horned Frog',         sci:'Limnonectes magnus',             status:'NT', group:'reptiles',    tag:'Frog',          island:'Mindanao',                           profiled:false },
  { name:'Luzon Fanged Frog',            sci:'Limnonectes macrocephalus',      status:'LC', group:'reptiles',    tag:'Frog',          island:'Luzon',                              profiled:false },
  { name:'Philippine Tree Frog',         sci:'Polypedates leucomystax',        status:'LC', group:'reptiles',    tag:'Frog',          island:'Widespread',                         profiled:false },
  { name:'Palawan Forest Turtle',        sci:'Leucocephalon yuwonoi',          status:'CR', group:'reptiles',    tag:'Turtle',        island:'Palawan',                            profiled:false },

  /* ══════════════════════════════════════════
     MARINE
  ══════════════════════════════════════════ */
  { name:'Dugong',                        sci:'Dugong dugon',                   status:'VU', group:'marine',      tag:'Marine Mammal', island:'Widespread Coast',                   profiled:true  },
  { name:'Whale Shark',                   sci:'Rhincodon typus',                status:'EN', group:'marine',      tag:'Shark',         island:'Widespread',                         profiled:true  },
  { name:'Whitefin Topeshark',            sci:'Hemitriakis leucoperiptera',     status:'CR', group:'marine',      tag:'Shark',         island:'Sulu Sea',                           profiled:true  },
  { name:'Blue-spotted Angelfish',        sci:'Chaetodontoplus caeruleopunctatus',status:'VU',group:'marine',     tag:'Fish',          island:'Central Philippines',                profiled:true  },
  { name:'Philippine Guitarfish',         sci:'Rhinobatos whitei',              status:'CR', group:'marine',      tag:'Ray',           island:'Sulu Sea',                           profiled:true  },
  { name:'Manila Sea Catfish',            sci:'Arius manillensis',              status:'VU', group:'marine',      tag:'Fish',          island:'Manila Bay · Laguna de Bay',         profiled:true  },
  { name:'Culion Silverside',             sci:'Atherinomorus elymus',           status:'DD', group:'marine',      tag:'Fish',          island:'Palawan',                            profiled:true  },
  { name:'Philippine Anchovy',            sci:'Encrasicholina philippinensis',  status:'LC', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Zulu Eelblenny',                sci:'Sticharium zulu',                status:'DD', group:'marine',      tag:'Fish',          island:'Sulu Sea',                           profiled:true  },
  { name:'Cuyo Coralbrotula',             sci:'Diancistrus cuyoensis',          status:'DD', group:'marine',      tag:'Fish',          island:'Cuyo Islands',                       profiled:true  },
  { name:'Philippine Chimaera',           sci:'Hydrolagus philippinensis',      status:'DD', group:'marine',      tag:'Deep Sea',      island:'Philippine Sea',                     profiled:true  },
  { name:'Short-horn Triangular Batfish', sci:'Halieutaea brevicornis',         status:'DD', group:'marine',      tag:'Fish',          island:'Philippine Sea',                     profiled:true  },
  { name:'Onefin Catshark',               sci:'Apristurus investigatoris',      status:'DD', group:'marine',      tag:'Shark',         island:'Philippine Sea',                     profiled:true  },
  { name:'Brackish Crabs',                sci:'Scylla spp.',                    status:'LC', group:'marine',      tag:'Crustacean',    island:'Widespread Coast',                   profiled:true  },
  { name:'Sinarapan',                     sci:'Mistichthys luzonensis',         status:'CR', group:'marine',      tag:'Fish',          island:'Bicol · Quezon',                     profiled:true  },
  { name:"Thielle's Anemonefish",         sci:'Amphiprion thiellei',            status:'DD', group:'marine',      tag:'Fish',          island:'Central Philippines',                profiled:true  },
  { name:'Azure Damselfish',              sci:'Altrichthys azurelineatus',      status:'VU', group:'marine',      tag:'Fish',          island:'Batangas',                           profiled:true  },
  { name:'Latigo Fairy Wrasse',           sci:'Cirrhilabrus briangreenei',      status:'DD', group:'marine',      tag:'Fish',          island:'Cebu',                               profiled:true  },
  { name:'Magma Fairy Wrasse',            sci:'Cirrhilabrus shutmani',          status:'DD', group:'marine',      tag:'Fish',          island:'Mindanao',                           profiled:true  },
  { name:'Jaguar Dottyback',              sci:'Pseudochromis moorei',           status:'DD', group:'marine',      tag:'Fish',          island:'Mindanao',                           profiled:true  },
  { name:'Whitechin Surgeonfish',         sci:'Acanthurus albimento',           status:'LC', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Philippine Flasher Wrasse',     sci:'Paracheilinus carpenteri',       status:'LC', group:'marine',      tag:'Fish',          island:'Central Philippines',                profiled:true  },
  { name:'Philippine Nautilus',           sci:'Nautilus pompilius',             status:'VU', group:'marine',      tag:'Cephalopod',    island:'Widespread',                         profiled:true  },
  { name:'Sulu Dragonfish',               sci:'Eustomias suluensis',            status:'DD', group:'marine',      tag:'Deep Sea',      island:'Sulu Sea',                           profiled:true  },
  /* — unprofile marine — */
  { name:'Bumphead Parrotfish',           sci:'Bolbometopon muricatum',         status:'VU', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Napoleon Wrasse',               sci:'Cheilinus undulatus',            status:'EN', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Scalloped Hammerhead Shark',    sci:'Sphyrna lewini',                 status:'CR', group:'marine',      tag:'Shark',         island:'Widespread',                         profiled:false },
  { name:'Oceanic Whitetip Shark',        sci:'Carcharhinus longimanus',        status:'CR', group:'marine',      tag:'Shark',         island:'Philippine Sea',                     profiled:false },
  { name:'Reef Manta Ray',                sci:'Mobula alfredi',                 status:'VU', group:'marine',      tag:'Ray',           island:'Widespread',                         profiled:false },
  { name:'Oceanic Manta Ray',             sci:'Mobula birostris',               status:'EN', group:'marine',      tag:'Ray',           island:'Philippine Sea',                     profiled:false },
  { name:'Philippine Seahorse',           sci:'Hippocampus comes',              status:'VU', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Pygmy Seahorse',                sci:'Hippocampus bargibanti',         status:'VU', group:'marine',      tag:'Fish',          island:'Visayas · Palawan',                  profiled:false },
  { name:'Mandarin Fish',                 sci:'Synchiropus splendidus',         status:'LC', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Giant Clam',                    sci:'Tridacna gigas',                 status:'VU', group:'marine',      tag:'Mollusc',       island:'Widespread',                         profiled:false },
  { name:'Blue-ringed Octopus',           sci:'Hapalochlaena spp.',             status:'DD', group:'marine',      tag:'Cephalopod',    island:'Widespread',                         profiled:false },
  { name:'Flamboyant Cuttlefish',         sci:'Metasepia pfefferi',             status:'DD', group:'marine',      tag:'Cephalopod',    island:'Visayas · Mindanao',                 profiled:false },
  { name:'Pelagic Thresher Shark',        sci:'Alopias pelagicus',              status:'EN', group:'marine',      tag:'Shark',         island:'Philippine Sea',                     profiled:false },
  { name:'Milkfish',                      sci:'Chanos chanos',                  status:'LC', group:'marine',      tag:'Fish',          island:'Widespread',                         profiled:false },

  /* ══════════════════════════════════════════
     INSECTS & INVERTEBRATES
  ══════════════════════════════════════════ */
  { name:'Atlas Moth',                    sci:'Attacus atlas',                  status:'LC', group:'insects',     tag:'Moth',          island:'Widespread',                         profiled:true  },
  { name:'Luzon Peacock Swallowtail',     sci:'Papilio chikae',                 status:'EN', group:'insects',     tag:'Butterfly',     island:'Luzon',                              profiled:true  },
  { name:'Magellan Birdwing',             sci:'Troides magellanus',             status:'VU', group:'insects',     tag:'Butterfly',     island:'Palawan · Cebu',                     profiled:true  },
  { name:'Palawan Birdwing',              sci:'Trogonoptera trojana',           status:'VU', group:'insects',     tag:'Butterfly',     island:'Palawan',                            profiled:true  },
  { name:"Semper's Birdwing",             sci:'Atrophaneura semperi',           status:'VU', group:'insects',     tag:'Butterfly',     island:'Luzon',                              profiled:true  },
  { name:'Emerald Swallowtail',           sci:'Papilio palinurus',              status:'LC', group:'insects',     tag:'Butterfly',     island:'Palawan · Mindanao',                 profiled:true  },
  { name:'Scarlet Mormon',                sci:'Papilio rumanzovia',             status:'LC', group:'insects',     tag:'Butterfly',     island:'Widespread',                         profiled:true  },
  { name:'Philippine Tiger Beetle',       sci:'Cicindela spp.',                 status:'DD', group:'insects',     tag:'Beetle',        island:'Widespread',                         profiled:true  },
  { name:'Philippine Firefly',            sci:'Pteroptyx spp.',                 status:'VU', group:'insects',     tag:'Beetle',        island:'Widespread',                         profiled:true  },
  { name:'Mindoro Stick Insect',          sci:'Conlephasma enigma',             status:'DD', group:'insects',     tag:'Phasmatodea',   island:'Mindoro',                            profiled:true  },
  { name:'Philippine Damselfly',          sci:'Risiocnemis spp.',               status:'DD', group:'insects',     tag:'Odonata',       island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Dragonfly',          sci:'Neurothemis terminata',          status:'LC', group:'insects',     tag:'Odonata',       island:'Widespread',                         profiled:true  },
  { name:'Philippine Longhorn Beetle',    sci:'Batocera spp.',                  status:'DD', group:'insects',     tag:'Beetle',        island:'Widespread',                         profiled:true  },
  { name:'Philippine Cicada',             sci:'Dundubia spp.',                  status:'DD', group:'insects',     tag:'Hemiptera',     island:'Widespread',                         profiled:true  },
  { name:'Philippine Tarantula',          sci:'Orphnaecus spp.',                status:'DD', group:'insects',     tag:'Spider',        island:'Widespread',                         profiled:true  },
  { name:'Philippine Walking Leaf',       sci:'Phyllium philippinicum',         status:'LC', group:'insects',     tag:'Phasmatodea',   island:'Luzon',                              profiled:true  },
  { name:'Philippine Praying Mantis',     sci:'Hierodula philippina',           status:'LC', group:'insects',     tag:'Mantodea',      island:'Widespread',                         profiled:true  },
  { name:'Philippine Giant Centipede',    sci:'Scolopendra dehaani',            status:'LC', group:'insects',     tag:'Centipede',     island:'Widespread',                         profiled:true  },
  { name:'Blue Crow Butterfly',           sci:'Euploea midamus',                status:'LC', group:'insects',     tag:'Butterfly',     island:'Widespread',                         profiled:true  },
  { name:'Philippine Weaver Ant',         sci:'Oecophylla smaragdina',          status:'LC', group:'insects',     tag:'Hymenoptera',   island:'Widespread',                         profiled:true  },
  { name:'Philippine Giant Forest Scorpion',sci:'Heterometrus longimanus',      status:'LC', group:'insects',     tag:'Scorpion',      island:'Widespread',                         profiled:true  },
  { name:'Coconut Rhinoceros Beetle',     sci:'Oryctes rhinoceros',             status:'LC', group:'insects',     tag:'Beetle',        island:'Widespread',                         profiled:true  },
  { name:'Philippine Giant Water Bug',    sci:'Lethocerus indicus',             status:'LC', group:'insects',     tag:'Hemiptera',     island:'Widespread',                         profiled:true  },
  { name:'Philippine Assassin Bug',       sci:'Sycanus spp.',                   status:'DD', group:'insects',     tag:'Hemiptera',     island:'Widespread',                         profiled:true  },
  /* — unprofile insects — */
  { name:'Philippine Stag Beetle',        sci:'Dorcus spp.',                    status:'DD', group:'insects',     tag:'Beetle',        island:'Luzon · Mindanao',                   profiled:false },
  { name:'Philippine Mole Cricket',       sci:'Gryllotalpa spp.',               status:'DD', group:'insects',     tag:'Cricket',       island:'Widespread',                         profiled:false },
  { name:'Giant Philippine Millipede',    sci:'Thyropygus spp.',                status:'DD', group:'insects',     tag:'Myriapoda',     island:'Mindanao · Palawan',                 profiled:false },
  { name:'Philippine Jewel Beetle',       sci:'Chrysochroa spp.',               status:'DD', group:'insects',     tag:'Beetle',        island:'Widespread',                         profiled:false },
  { name:'Philippine Plume Moth',         sci:'Pterophorus spp.',               status:'DD', group:'insects',     tag:'Moth',          island:'Widespread',                         profiled:false },
  { name:'Philippine Carpenter Bee',      sci:'Xylocopa latipes',               status:'LC', group:'insects',     tag:'Hymenoptera',   island:'Widespread',                         profiled:false },
  { name:'Philippine Huntsman Spider',    sci:'Heteropoda spp.',                status:'DD', group:'insects',     tag:'Spider',        island:'Widespread',                         profiled:false },
  { name:'Mindanao Dobsonfly',            sci:'Archichauliodes spp.',           status:'DD', group:'insects',     tag:'Megaloptera',   island:'Mindanao',                           profiled:false },
  { name:'Golden Birdwing',               sci:'Troides rhadamantus',            status:'VU', group:'insects',     tag:'Butterfly',     island:'Luzon · Mindanao',                   profiled:false },
  { name:'Philippine Hawk Moth',          sci:'Theretra spp.',                  status:'DD', group:'insects',     tag:'Moth',          island:'Widespread',                         profiled:false },

  /* ══════════════════════════════════════════
     FRESHWATER
  ══════════════════════════════════════════ */
  { name:'Tawilis',                          sci:'Sardinella tawilis',           status:'VU', group:'freshwater',  tag:'Fish',          island:'Taal Lake · Batangas',               profiled:true  },
  { name:'Luzon Ricefish',                   sci:'Oryzias luzonensis',           status:'VU', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:'Philippine Silver Perch',          sci:'Leiopotherapon plumbeus',      status:'LC', group:'freshwater',  tag:'Fish',          island:'Luzon · Visayas',                    profiled:true  },
  { name:'Mindanao Rasbora',                 sci:'Rasbora philippina',           status:'DD', group:'freshwater',  tag:'Fish',          island:'Mindanao',                           profiled:true  },
  { name:'Luzon River Pipefish',             sci:'Microphis pleurostictus',      status:'DD', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:"Schoppe's Barb",                   sci:'Cyclocheilichthys schoppeae',  status:'VU', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:'Palawan Blue-clawed Freshwater Crab',sci:'Insulamon palawanense',      status:'EN', group:'freshwater',  tag:'Crustacean',    island:'Palawan',                            profiled:true  },
  { name:'Giant Freshwater Prawn',           sci:'Macrobrachium rosenbergii',    status:'LC', group:'freshwater',  tag:'Crustacean',    island:'Widespread',                         profiled:true  },
  { name:'Giant Mottled Eel',                sci:'Anguilla marmorata',           status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Philippine Stream Goby',           sci:'Stiphodon elegans',            status:'LC', group:'freshwater',  tag:'Fish',          island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Philippine Mudskipper',            sci:'Periophthalmus gracilis',      status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Lake Lanao Barb',                  sci:'Barbodes lanaoensis',          status:'CR', group:'freshwater',  tag:'Fish',          island:'Mindanao',                           profiled:true  },
  { name:'Philippine Snakehead',             sci:'Channa striata',               status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Philippine Glass Goby',            sci:'Gobiopterus lacustris',        status:'DD', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:'Palawan Barb',                     sci:'Barbodes palawanensis',        status:'VU', group:'freshwater',  tag:'Fish',          island:'Palawan',                            profiled:true  },
  { name:'Philippine Freshwater Shrimp',     sci:'Caridina philippinensis',      status:'DD', group:'freshwater',  tag:'Crustacean',    island:'Luzon',                              profiled:true  },
  { name:'Philippine Stone Loach',           sci:'Homaloptera orthogoniata',     status:'DD', group:'freshwater',  tag:'Fish',          island:'Luzon · Mindanao',                   profiled:true  },
  { name:'Palawan Freshwater Stingray',      sci:'Himantura chaophraya',         status:'EN', group:'freshwater',  tag:'Fish',          island:'Palawan',                            profiled:true  },
  { name:'Philippine Freshwater Needlefish', sci:'Xenentodon cancila',           status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Philippine Mountain Goby',         sci:'Sicyopus discordipinnis',      status:'LC', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:'Philippine Forest Stream Crab',    sci:'Sundathelphusa spp.',          status:'DD', group:'freshwater',  tag:'Crustacean',    island:'Widespread',                         profiled:true  },
  { name:'Philippine Glassperch',            sci:'Ambassis miops',               status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:true  },
  { name:'Lizard Goby',                      sci:'Rhinogobius philippinus',      status:'DD', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:true  },
  { name:'Philippine Pond Turtle',           sci:'Siebenrockiella crassicollis', status:'VU', group:'freshwater',  tag:'Turtle',        island:'Luzon · Palawan',                    profiled:true  },
  /* — unprofile freshwater — */
  { name:'Philippine Catfish',               sci:'Clarias batrachus',            status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Janss\'s Pipefish',                sci:'Microphis jaansii',            status:'DD', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:false },
  { name:'Philippine Giant Gourami',         sci:'Osphronemus goramy',           status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Hoven\'s Carp',                    sci:'Leptobarbus hoevenii',         status:'EN', group:'freshwater',  tag:'Fish',          island:'Mindanao · Palawan',                 profiled:false },
  { name:'Philippine Freshwater Mussel',     sci:'Corbicula spp.',               status:'DD', group:'freshwater',  tag:'Mollusc',       island:'Widespread',                         profiled:false },
  { name:'Laguna de Bay Goby',               sci:'Glossogobius giuris',          status:'LC', group:'freshwater',  tag:'Fish',          island:'Luzon',                              profiled:false },
  { name:'Philippine Walking Catfish',       sci:'Clarias magur',                status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Freshwater Halfbeak',              sci:'Dermogenys pusilla',           status:'LC', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:false },
  { name:'Lake Mainit Goby',                 sci:'Glossogobius celebius',        status:'LC', group:'freshwater',  tag:'Fish',          island:'Mindanao',                           profiled:false },
  { name:'Philippine Spiny Eel',             sci:'Mastacembelus spp.',           status:'DD', group:'freshwater',  tag:'Fish',          island:'Widespread',                         profiled:false },

  /* ══════════════════════════════════════════
     LOST SPECIES
  ══════════════════════════════════════════ */
  { name:'Luzon Stegodon',               sci:'Stegodon luzonensis',             status:'EX', group:'extinct',     tag:'Prehistoric',   island:'Luzon',                              profiled:true  },
  { name:'Philippine Rhinoceros',        sci:'Rhinoceros philippinensis',       status:'EX', group:'extinct',     tag:'Prehistoric',   island:'Luzon',                              profiled:true  },
  { name:'Luzon Giant Tortoise',         sci:'Geochelone sp.',                  status:'EX', group:'extinct',     tag:'Prehistoric',   island:'Luzon',                              profiled:true  },
  { name:'Cebu Warty Pig',               sci:'Sus cebifrons negrinus',          status:'EX', group:'extinct',     tag:'Modern',        island:'Cebu',                               profiled:true  },
  { name:'Cebu Large Sparrowhawk',       sci:'Accipiter griseiceps',            status:'EX', group:'extinct',     tag:'Modern',        island:'Cebu',                               profiled:true  },
  { name:'Lake Lanao Cyprinids',         sci:'Barbodes spp. (18 species)',      status:'EX', group:'extinct',     tag:'Modern',        island:'Mindanao',                           profiled:true  },
  { name:'Negros Naked-backed Fruit Bat',sci:'Dobsonia chapmani',               status:'PE', group:'extinct',     tag:'Modern',        island:'Negros · Cebu',                      profiled:true  },
  { name:'Philippine Giant Cave Bat',    sci:'Otopteropus cartilagonodus',      status:'PE', group:'extinct',     tag:'Modern',        island:'Luzon',                              profiled:true  },
  { name:'Cebu Flowerpecker',            sci:'Dicaeum quadricolor',             status:'RD', group:'extinct',     tag:'Rediscovered',  island:'Cebu',                               profiled:true  },
  { name:'Calamian Deer',                sci:'Axis calamianensis',              status:'RD', group:'extinct',     tag:'Rediscovered',  island:'Calamian Islands',                   profiled:true  },
  { name:'Palawan Bearded Pig',          sci:'Sus barbatus ahoenobarbus',       status:'RD', group:'extinct',     tag:'Rediscovered',  island:'Palawan',                            profiled:true  },
  { name:'Cebu Visayan Wattled Broadbill',sci:'Sarcophanops samarensis',        status:'PE', group:'extinct',     tag:'Modern',        island:'Cebu',                               profiled:false },
  { name:'Panay Monitor Lizard',         sci:'Varanus mabitang',                status:'PE', group:'extinct',     tag:'Modern',        island:'Panay',                              profiled:false },

];

/* helper — expose to other scripts */
if (typeof module !== 'undefined') module.exports = SPECIES;
